global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels: {environment: local-monitoring}
rule_files:
  - /etc/prometheus/rules.yml
scrape_configs:
  - job_name: api
    metrics_path: /metrics/api
    static_configs:
      - targets: ['collector:9800']
  - job_name: pre-send
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['pre-send:19093']
  - job_name: publication-recovery
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['publication-recovery:19098']
  - job_name: skt-sender
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['skt-sender:19091']
  - job_name: kt-sender
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['kt-sender:19091']
  - job_name: lgu-sender
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['lgu-sender:19091']
  - job_name: webhook-receive
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['webhook-receive:19089']
  - job_name: result-manager
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['result-manager:19094']
  - job_name: complete-manager
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['complete-manager:19095']
  - job_name: webhook-sender
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['webhook-sender:19096']
  - job_name: tcp-sender
    metrics_path: /actuator/prometheus
    static_configs:
      - targets: ['tcp-sender:19097']
  - job_name: kafka-observer
    static_configs:
      - targets: ['collector:9800']
  - job_name: redis
    static_configs:
      - targets: ['redis-exporter:9121']
  - job_name: postgres
    static_configs:
      - targets: ['postgres-exporter:9187']
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: loki
    static_configs:
      - targets: ['loki:3100']
  - job_name: alloy
    static_configs:
      - targets: ['alloy:12345']
