server:
  port: ${EVENT_REFERENCE_CACHE_PORT:8098}
  shutdown: graceful

spring:
  application:
    name: event-reference-cache
  lifecycle:
    timeout-per-shutdown-phase: 30s
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      database: ${REDIS_DATABASE:0}
      connect-timeout: ${REDIS_CONNECT_TIMEOUT:200ms}
      timeout: ${REDIS_TIMEOUT:200ms}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    listener:
      ack-mode: record
      concurrency: ${EVENT_REFERENCE_CACHE_CONCURRENCY:2}
    consumer:
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        "[allow.auto.create.topics]": false

management:
  endpoint:
    health:
      probes:
        enabled: true
        add-additional-paths: true
  server:
    address: 127.0.0.1
    port: ${EVENT_REFERENCE_CACHE_METRICS_PORT:19088}
  endpoints:
    web:
      exposure:
        include: health
