-- Only run against the local Compose delivery database.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
INSERT INTO users (username, password, status, created_at, updated_at)
VALUES ('local-user', crypt('local-password', gen_salt('bf')), 'ACTIVE', now(), now())
ON CONFLICT (username) DO NOTHING;
COMMIT;
