-- Only run against the local Compose delivery database.
BEGIN;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
INSERT INTO users (username, password, status, created_at, updated_at)
VALUES ('local-user', crypt('local-password', gen_salt('bf')), 'ACTIVE', now(), now())
ON CONFLICT (username) DO NOTHING;
CREATE TABLE IF NOT EXISTS client_event_contracts (
    client_id bigint PRIMARY KEY REFERENCES users(id),
    enabled boolean NOT NULL DEFAULT true,
    tps_limit integer NOT NULL CHECK (tps_limit > 0),
    quota_general bigint NOT NULL CHECK (quota_general > 0),
    quota_noti bigint NOT NULL CHECK (quota_noti > 0),
    quota_adv bigint NOT NULL CHECK (quota_adv > 0),
    quota_alert bigint NOT NULL CHECK (quota_alert > 0),
    updated_at timestamptz NOT NULL DEFAULT now()
);
INSERT INTO client_event_contracts (client_id, tps_limit, quota_general, quota_noti, quota_adv, quota_alert)
SELECT id, 100, 100000, 100000, 100000, 100000 FROM users WHERE username = 'local-user'
ON CONFLICT (client_id) DO NOTHING;
COMMIT;
